import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ColorSchemeScript, createTheme, MantineProvider } from "@mantine/core";
import { Shell } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  fontFamily: inter.style.fontFamily,
});

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const defaultColorScheme = "dark";
  /**
   * On `suppressHydrationWarning`:
   * There will be a mismatch between the client and server rendered HTML.
   * The mismatch is `data-mantine-color-scheme="light"` on the `html` element.
   * This is expected and can be safely ignored.
   */
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme={defaultColorScheme} />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={theme} defaultColorScheme={defaultColorScheme}>
          <Shell>{children}</Shell>
        </MantineProvider>
      </body>
    </html>
  );
};

export default Layout;
