import { BASE_API } from "@/api/swapi";
import type { SwapiEntity } from "@/types";

/**
 * We can dynamically convert SWAPI URLs to internal URLs because we map the API to our webapp.
 *
 * Code partially generated by AI.
 */
const getInternalUrl = (swapiurl: string): string => {
  const parts = swapiurl.split("/api/")[1].split("/").filter(Boolean);
  if (parts.length >= 2) {
    return `/${parts[0]}/${parts[1]}`;
  }
  if (parts.length === 1) {
    return `/${parts[0]}`;
  }
  return "/";
};

const getEntityDescriptor = (entity: SwapiEntity): string =>
  entity.name || entity.title || "";

const isSwapiUrl = (value: string): boolean => {
  return value.startsWith(BASE_API);
};

export { getInternalUrl, isSwapiUrl, getEntityDescriptor };
